// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://adghzpohumdywcrnzxum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkZ2h6cG9odW1keXdjcm56eHVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNzI0ODMsImV4cCI6MjA3Mjc0ODQ4M30.uR6A3tNiFZ83auAsfsBB2RBXeFfjhvmnIA6wv9oqnrE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});